# Cloudflare Pages Configuration
name = "shiueo-resume"
compatibility_date = "2025-05-25"
compatibility_flags = ["nodejs_compat"]

# Pages build output directory
pages_build_output_dir = ".svelte-kit/cloudflare"